name: geo
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - geopandas
  - dask-geopandas
  - graphviz # dask visualization
  - pandas
  - osmnx
  - networkx
  - openpyxl
  - jupyterlab
  - spyder # !don't install on vm
  - xgboost
  - scikit-learn
  - scipy # stats & interpolate
  - tqdm
  - h3-py
  - seaborn
  - contextily
  - spopt
  - libpysal
  - fastparquet
  - pyarrow
  - missingno
  - selenium
  - ipycytoscape
  - python-graphviz
  - zarr
  - xarray
  - pooch
  - s3fs
  - dask distributed
  - dask-labextension

